/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkspaceChatRouteImport } from './routes/_workspace.chat'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceInboxRouteImport } from './routes/_workspace.inbox'
import { Route as WorkspaceInsightsRouteImport } from './routes/_workspace.insights'
import { Route as WorkspaceSearchRouteImport } from './routes/_workspace.search'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceTopicsRouteImport } from './routes/_workspace.topics'
import { Route as WorkspaceKnowledgeIdRouteImport } from './routes/_workspace.knowledge.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceInboxRoute = WorkspaceInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceInsightsRoute = WorkspaceInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSearchRoute = WorkspaceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTopicsRoute = WorkspaceTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKnowledgeIdRoute = WorkspaceKnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof WorkspaceChatRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/inbox': typeof WorkspaceInboxRoute
  '/insights': typeof WorkspaceInsightsRoute
  '/search': typeof WorkspaceSearchRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/topics': typeof WorkspaceTopicsRoute
  '/knowledge/$id': typeof WorkspaceKnowledgeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof WorkspaceChatRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/inbox': typeof WorkspaceInboxRoute
  '/insights': typeof WorkspaceInsightsRoute
  '/search': typeof WorkspaceSearchRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/topics': typeof WorkspaceTopicsRoute
  '/knowledge/$id': typeof WorkspaceKnowledgeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_workspace/chat': typeof WorkspaceChatRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/inbox': typeof WorkspaceInboxRoute
  '/_workspace/insights': typeof WorkspaceInsightsRoute
  '/_workspace/search': typeof WorkspaceSearchRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/topics': typeof WorkspaceTopicsRoute
  '/_workspace/knowledge/$id': typeof WorkspaceKnowledgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/inbox'
    | '/insights'
    | '/search'
    | '/settings'
    | '/topics'
    | '/knowledge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/inbox'
    | '/insights'
    | '/search'
    | '/settings'
    | '/topics'
    | '/knowledge/$id'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/signup'
    | '/_workspace/chat'
    | '/_workspace/dashboard'
    | '/_workspace/inbox'
    | '/_workspace/insights'
    | '/_workspace/search'
    | '/_workspace/settings'
    | '/_workspace/topics'
    | '/_workspace/knowledge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/chat': {
      id: '/_workspace/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/inbox': {
      id: '/_workspace/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof WorkspaceInboxRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/insights': {
      id: '/_workspace/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof WorkspaceInsightsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/search': {
      id: '/_workspace/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof WorkspaceSearchRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/topics': {
      id: '/_workspace/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof WorkspaceTopicsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/knowledge/$id': {
      id: '/_workspace/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof WorkspaceKnowledgeIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceInboxRoute: typeof WorkspaceInboxRoute
  WorkspaceInsightsRoute: typeof WorkspaceInsightsRoute
  WorkspaceSearchRoute: typeof WorkspaceSearchRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTopicsRoute: typeof WorkspaceTopicsRoute
  WorkspaceKnowledgeIdRoute: typeof WorkspaceKnowledgeIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceInboxRoute: WorkspaceInboxRoute,
  WorkspaceInsightsRoute: WorkspaceInsightsRoute,
  WorkspaceSearchRoute: WorkspaceSearchRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTopicsRoute: WorkspaceTopicsRoute,
  WorkspaceKnowledgeIdRoute: WorkspaceKnowledgeIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
